### ISSUE TITLE
line breaks are not respected

### ISSUE THREAD

**Issue by woss** [chevdor/tera-cli#19]
this is the [current template ](https://github.com/paritytech/polkadot_network_directory/blob/master/templates/summary.md.tera#L59) MD and rendered output:
![image](https://user-images.githubusercontent.com/80440/207665423-276cec47-70fa-4349-b46c-33ad86ec5832.png)

This is how it should render it:
![image](https://user-images.githubusercontent.com/80440/207665562-a5feca90-14e0-4b22-8a12-e6494d762466.png)

The wrongly formatted MD will be ignored by the `mdbook` and thus never rendered into the HTML nor served. 

I think the issue is with the CLI, but i am not 100% sure. Better to have it reported here than [there ](https://github.com/paritytech/polkadot_network_directory) since the polkadot_network_discovery is only using this cli.

I've also looked into the code and couldn't find an obvious fix. I did find out that the tera has the [linebreakbr](https://tera.netlify.app/docs/#linebreaksbr) utility but i couldn't make it work.

**Comment by chevdor** [comment]
The line breaks are respected but this is a tricky topic...

If there would be an issue, that would have had to be reported in the tera repo itself but I don't think there is.

Did you expect an empty line before the list ?
There is none becasue of the `-` you have here:
<img width="139" alt="image" src="https://user-images.githubusercontent.com/738724/211309904-66f71d3c-19dc-40ea-8fc1-72ce1466f1bd.png">

The `-` eats the spaces and empty lines.

I am closing because this is very likely the problem you ran into. Please reopen if there is another issue.
Try playing with `{% foo %}` vs `{%- foo %}` vs `{% foo -%}` vs `{%- foo -%}`
